### ISSUE TITLE
Problems to sync

### ISSUE THREAD

**Issue by der-lu** [sebastianpech/Zotero-Remarkable#5]
unfortunately, i cannot sync anymore. I gt the following error

Traceback (most recent call last):
  File "/home/derlu/Progs/Zotero-Remarkable/sync.py", line 75, in <module>
    process_files(delete=args.delete, download=args.download)
  File "/home/derlu/Progs/Zotero-Remarkable/sync.py", line 53, in process_files
    files_on_remarkable, files_on_local = get_files()
  File "/home/derlu/Progs/Zotero-Remarkable/sync.py", line 48, in get_files
    files_on_remarkable = set([f.split('\t')[-1] for f in rmapi(f"ls {RM_FOLDER}")])
  File "/home/derlu/Progs/Zotero-Remarkable/sync.py", line 23, in rmapi
    return subprocess.check_output(f"{RMAPI_BIN} {cmd}", shell=True, stderr=subprocess.STDOUT).decode("utf-8").split('\n')[0:-1]
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/home/derlu/Progs/rmapi/ ls Paper' returned non-zero exit status 126.

What is happening?

Greetings 

derlu

**Comment by der-lu** [comment]
The error disappeared over night. cant explain it
